version: "3.8"

services:
  api:
    container_name: lang
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    volumes:
      - ./:/app
  api_dev:
    container_name: lang_dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - PYTHONDONTWRITEBYTECODE=1
    command: python -m uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    networks:
      - custom_network

networks:
  custom_network:
    external: true
